---
version: '3'
services:

    first:
        image: testfedora
        build:
            context: .
        privileged: true
        entrypoint: /localbpf/entrypoints/first.sh
        volumes:
            - ./:/localbpf
        networks:
            primary:
                ipv4_address: 10.111.220.11
            second:
                ipv4_address: 10.111.221.11

    second:
        image: testfedora
        privileged: true
        volumes:
            - ./:/localbpf
        entrypoint: /localbpf/entrypoints/second.sh
        networks:
            second:
                ipv4_address: 10.111.221.21
            third:
                ipv4_address: 10.111.222.21
    third:
        image: testfedora
        privileged: true
        volumes:
            - ./:/localbpf
        entrypoint: /localbpf/entrypoints/third.sh
        networks:
            third:
                ipv4_address: 10.111.222.22

networks:
    primary:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.220.1/24
    second:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.221.1/24
    third:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.222.1/24
        