---
version: '3'
services:

    server:
        image: testfedora
        build:
            context: .
        privileged: true
        entrypoint: /local/entrypoints/server.sh
        volumes:
            - ./:/local
        networks:
            primary:
                ipv4_address: 10.111.220.11
            server_to_router:
                ipv4_address: 10.111.221.11

    router:
        image: testfedora
        privileged: true
        volumes:
            - ./:/local
        entrypoint: /local/entrypoints/router.sh
        networks:
            server_to_router:
                ipv4_address: 10.111.221.21
            router_to_client:
                ipv4_address: 10.111.222.21
    client:
        image: testfedora
        privileged: true
        volumes:
            - ./:/local
        entrypoint: /local/entrypoints/client.sh
        networks:
            router_to_client:
                ipv4_address: 10.111.222.22

networks:
    primary:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.220.1/24
    server_to_router:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.221.1/24
    router_to_client:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.222.1/24
        
